### ISSUE TITLE
Support for UTi220A Pro

### ISSUE THREAD

**Issue by c1400700226** [Santi-hr/UNI-T-Thermal-Utilities#2]
Hi, recently I bought an UTi220A Pro, it's just an renamed UTi260b with different shell color. But when I use the script to convert bmp files, the edge of the image has one or two lines corrupted. I am a programming newbie and couldn't find out why😅, so could you please give some help? Here are two samples converted with "-bmp -nf", thanks in advance!
[sample.zip](https://github.com/Santi-hr/UNI-T-Thermal-Utilities/files/6596963/sample.zip)

**Comment by Santi-hr** [comment]
Hello, I checked the files and, as you said, their format is exactly as the ones from the UTi260B. Could you tell me what firmware version does your camera report?
Thanks to this issue I discovered a bug when exporting the image to bmp. The first row was not being overwriten properly.

However, for the right and lower edges it seems that this is actually what is stored on the file. In my samples the lower edge shows the same behaviour. Attached Excel file with the bytes from your samples and two of mine. On the "Raw thermal viewer" sheet you can see the bytes stored for the thermal image. Change between samples using cell B2.
[Raw data comparison.xlsx](https://github.com/Santi-hr/UNI-T-Thermal-Utilities/files/6604817/Raw.data.comparison.xlsx)

I suspect it is from the sensor edge and that it is removed when showing on the display by some kind of interpolation (Keep in mind that the image is 320x240 but the IR sensor is only 256x192). The last row could be numbers, but it is unlikely as it is always similar between images of the same camera.
I made a quick gif to compare the stored and extracted images. It seems that they are not exactly the same. Some shift can be apreciated and the sky bands change a bit.
![b_gif](https://user-images.githubusercontent.com/9913071/120938241-217b4e80-c712-11eb-9139-b30758eb042e.gif)

**Comment by c1400700226** [comment]
Thanks for your reply! My camera firmware version is v1.1.7.

And I also found that the bottom and right edge issue isn't caused by the script, the manufacturer's software also shows that.
