### ISSUE TITLE
Port to Octave

### ISSUE THREAD

**Issue by NotAProgrammerAtAll** [Santi-hr/UNI-T-Thermal-Utilities#4]
``
[readthermalBmp.txt](https://github.com/Santi-hr/UNI-T-Thermal-Utilities/files/10473182/readthermalBmp.txt)

I am not skilled with python - I took your instructions and put something together in octave. It seems to work except for reading the colour map/palette from the original file. I would appreciate help with that. 

I have attached a *.txt file - it can be converted to *.m to run with octave.

It opens a file called 'IMG_0003.bmp' displays the corresponding BMP, and reads the header and a clean BMP.  It displays the clean BMP in another figure and allows the user to select from a range of palettes. 
Thanks.

**Comment by Santi-hr** [comment]
Hello, I will try to give it a go this week. As soon as I develop something I will post here for you to check.

**Comment by Santi-hr** [comment]
[edit_readthermalBmp.txt](https://github.com/Santi-hr/UNI-T-Thermal-Utilities/files/10530886/edit_readthermalBmp.txt)

Added a section to read the pallete from the file and display it on a separate figure. Check if this is was you were looking for!

Also while testing with some sample images I discovered a bug when reading negative temperatures. The variables MaxTemp, MinTemp and CentTemp should be read as signed ints.

**Comment by NotAProgrammerAtAll** [comment]
> [edit_readthermalBmp.txt](https://github.com/Santi-hr/UNI-T-Thermal-Utilities/files/10530886/edit_readthermalBmp.txt)
> 
> Added a section to read the pallete from the file and display it on a separate figure. Check if this is was you were looking for!
> 
> Also while testing with some sample images I discovered a bug when reading negative temperatures. The variables MaxTemp, MinTemp and CentTemp should be read as signed ints.

Thanks, it works now. I am still getting my head around the code you added. I am looking forward to your next update.
